# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Zarguzashtam
tagline:             " "
url:                 http://robnsngh.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Robin Singh
  url:               https://twitter.com/robnsngh
  email:             robnsngh@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/robnsngh/robnsngh.github.io

pages_list:
  Left Brain: '/left-brain/index.html'
  Right Brain: '/right-brain/index.html'
  Lines: '/lines/index.html'
  Archive: '/archive'
  About: '/about'
